version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend/deckSelector
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/deckSelector:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend